pipeline:
  build:
    image: onaio/python:${PYTHON_VERSION}
    commands:
      - apt-get install -qq python-apt python-pycurl
      - pip install --upgrade pip
      - pip install ansible
      - ansible-galaxy install -r requirements.yml
      - ansible-playbook -i "127.0.0.1,"  tests/test.yml --syntax-check
      - ansible-playbook -i "127.0.0.1," tests/test.yml --connection=local --become
      - >
        ansible-playbook -i "127.0.0.1," tests/test.yml --connection=local --become
        | grep -q 'changed=0.*failed=0'
        && (echo 'Idempotence test: pass' && exit 0)
        || (echo 'Idempotence test: fail' && exit 1)
      - systemctl status django_example_app.service
      - echo $?
  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
        status: [success, failure]
        event: [push, tag]
matrix:
  PYTHON_VERSION:
    - 3.6
