pipeline:
  system:
    image: ubuntu:xenial
    labels:
      - com.onaio.ansible-django.test
    name: xxxxuyyuyy
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    init: /usr/lib/systemd/systemd
    detach: true
  exec:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - TERM=xterm-256color
    commands:
      - echo "$(docker ps)"
      - CONTAINER_ID="$(docker ps -qf "label=com.onaio.ansible-django.test")"
      - test -n "$CONTAINER_ID" || { echo "Container Not Found"; exit 1 ;}
      - docker exec -t "$CONTAINER_ID" apt update
      - docker exec -t "$CONTAINER_ID" apt install -y git sudo python-pip python-minimal software-properties-common
      - docker exec -t "$CONTAINER_ID" pip install ansible
      - docker exec -t "$CONTAINER_ID" sh -c "apt-get -y clean && apt-get -y autoclean"
      - docker exec -t "$CONTAINER_ID" ansible-galaxy install -r requirements.yml
      - docker exec -t "$CONTAINER_ID" ansible-playbook -i "127.0.0.1,"  tests/test.yml --syntax-check
      - docker exec -t "$CONTAINER_ID" ansible-playbook -i "127.0.0.1," tests/test.yml --connection=local --become
      - docker exec -t "$CONTAINER_ID" systemctl status django_example_app.service
      - docker exec -t "$CONTAINER_ID" echo $?
  notify:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [success, failure]
      event: [push, tag]
