---
- name: Ensure `GnuPG` is installed
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: "yes"
  become: true
  become_user: root

- name: Add deadsnakes PPA
  ansible.builtin.apt_repository:
    repo: "{{ django_python_apt_ppa }}"
    state: present
  become: true
  become_user: root

- name: Install python packages
  ansible.builtin.apt:
    name: "{{ django_python_packages }}"
    state: present
    update_cache: "yes"
  become: true
  become_user: root

- name: Install virtualenv
  ansible.builtin.pip:
    name: "virtualenv"
    state: present
    executable: "{{ django_pip_executable }}"
  when: django_install_virtualenv
