---
- name: Ensure `GnuPG` is installed
  ansible.builtin.apt:
    name: gnupg
    state: present
    update_cache: "yes"
  become: true
  become_user: root

- name: Add deadsnakes PPA
  ansible.builtin.apt_repository:
    repo: "{{ django_python_apt_ppa }}"
    state: present
  become: true
  become_user: root
  register: deadsnakes_ppa
  retries: 3
  delay: 10
  until: deadsnakes_ppa is success

- name: Install python packages
  ansible.builtin.apt:
    name: "{{ django_python_packages }}"
    state: present
    update_cache: "yes"
  become: true
  become_user: root

- name: Install virtualenv
  ansible.builtin.apt:
    name: python3-virtualenv
    state: present
  become: true
  become_user: root
  when: django_install_virtualenv
