---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1
  roles:
    - role: onaio.django
      django_system_user: "django_example_app"
      django_system_user_home: "/home/{{ django_system_user }}"
      django_recreate_virtual_env: false
      django_manage_services: true
      django_codebase_path: "{{ django_system_user_home }}/app"
      django_versioned_path: "{{ django_codebase_path }}-versioned"
      django_checkout_path: "{{ django_versioned_path }}/{{ ansible_date_time['epoch'] }}"
      django_git_url: "https://github.com/onaio/onadata"
      django_system_wide_dependencies:
        - binutils
        - libproj-dev
        - gdal-bin
        - memcached
        - libmemcached-dev
        - build-essential
        - git
        - libssl-dev
        - libpq-dev
        - gfortran
        - libatlas-base-dev
        - libjpeg-dev
        - libxml2-dev
        - libxslt1-dev
        - zlib1g-dev
        - software-properties-common
        - ghostscript
        - python3-celery
        - python3-sphinx
        - pkg-config
        - gcc
        - automake
        - libtool
      django_pip_paths:
        - "{{ django_checkout_path }}/requirements/base.pip"
      django_wsgi_extra_configurations:
        - "ignore-sigpipe = true"
      django_git_version: "main"
      django_celery_app: "onadata.celeryapp"
      django_use_pipenv: false
      django_use_regular_old_pip: true
      django_enable_celery: true
      django_use_poetry: false
      django_local_settings_path: "{{ django_checkout_path }}/mysite/settings/local_settings.py"
      django_settings_module: "onadata.settings.default_settings"
      django_wsgi_module: "onadata.devwsgi:application"
      django_init_commands:
      django_top_python_statements:
        - import os
        - from decimal import Decimal
      django_bottom_python_statements:
        - test_var = Decimal(16)
        - SECRET_KEY = "secret"
      django_wsgi_env_variables:
        SOME_ENV: "Some value"
