---
- name: Converge
  hosts: all
  roles:
    - role: ansible-django
      django_system_user: "django_example_app"
      django_system_user_home: "/home/{{ django_system_user }}"
      django_recreate_virtual_env: false
      django_codebase_path: "{{ django_system_user_home }}/app"
      django_versioned_path: "{{ django_codebase_path }}-versioned"
      django_checkout_path: "{{ django_versioned_path }}/{{ ansible_date_time['epoch'] }}"
      django_git_url: "https://github.com/onaio/kaznet-web"
      django_git_version: "v1.1.8"
      django_celery_app: "kaznet"
      django_python_source_version: "3.8"
      django_python_version: "python3.8"
      django_use_pipenv: true
      django_use_regular_old_pip: false
      django_manage_services: true
      django_enable_celery: true
      django_use_poetry: false
      django_local_settings_path: "{{ django_checkout_path }}/kaznet/settings/local_settings.py"
      django_settings_module: "kaznet.settings.local_settings"
      django_wsgi_module: "kaznet.wsgi:application"
      django_init_commands:
      django_top_python_statements:
        - import os
        - from decimal import Decimal
      django_bottom_python_statements:
        - test_var = Decimal(16)
        - SECRET_KEY = "secret"
