---
- name: Converge
  hosts: all
  roles:
    - role: ansible-django
      vars:
        system_user: "django_example_app"
        system_user_home: "/home/{{ system_user }}"
        recreate_virtual_env: False
        codebase_path: "{{ system_user_home }}/app"
        versioned_path: "{{ codebase_path }}-versioned"
        checkout_path: "{{ versioned_path }}/{{ ansible_date_time['epoch'] }}"
        git_url: "https://github.com/moshthepitt/picha"
        git_version: "master"
        celery_app: "picha"
        python_source_version: "2.7"
        python_version: "python2.7"
        enable_celery: True
        local_settings_path: "{{ checkout_path }}/picha/local_settings.py"
        django_settings_module: "picha.settings"
        wsgi_module: "picha.wsgi:application"
        django_init_commands:
          - migrate --noinput
        pip_packages:
          - celery
          - uwsgi
          - 'redis==2.10.6'
        top_python_statements:
          - import os
          - from decimal import Decimal
        bottom_python_statements:
          - test_var = Decimal(16)
