---
name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Run Molecule tests
        uses: onaio/molecule-action@master

  release:
    name: Release
    needs:
      - test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.0.3
        with:
          galaxy_api_key: ${{ secrets.ansible_galaxy_api_key }}
