---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization.  # noqa 303
      command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_service_mgr == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1
  roles:
    - role: onaio.django
      django_system_user: "django_example_app"
      django_system_user_home: "/home/{{ django_system_user }}"
      django_recreate_virtual_env: false
      django_codebase_path: "{{ django_system_user_home }}/app"
      django_versioned_path: "{{ django_codebase_path }}-versioned"
      django_checkout_path: "{{ django_versioned_path }}/{{ ansible_date_time['epoch'] }}"
      django_git_url: "https://github.com/onaio/kaznet-web"
      django_git_version: "v1.1.8"
      django_celery_app: "kaznet"
      django_use_pipenv: true
      django_use_regular_old_pip: false
      django_manage_services: true
      django_enable_celery: true
      django_local_settings_path: "{{ django_checkout_path }}/kaznet/settings/local_settings.py"
      django_settings_module: "kaznet.settings.local_settings"
      django_wsgi_module: "kaznet.wsgi:application"
      django_settings_template_path: "molecule/use_settings_template/templates/local_settings.py.j2"
      django_init_commands:
