---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ansible-django-ubuntu-18.04
    image: solita/ubuntu-systemd:18.04
    dockerfile: Dockerfile.j2
    privileged: true
    command: /sbin/init
    env:
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
provisioner:
  name: ansible
verifier:
  name: testinfra
